// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX1hc2Y4AmDvR4rpYaRQ4JsIp_HjkVa3k',
    appId: '1:1049365967745:web:67d9e4cd55592e6c292e80',
    messagingSenderId: '1049365967745',
    projectId: 'alu-internship-app-63f4e',
    authDomain: 'alu-internship-app-63f4e.firebaseapp.com',
    storageBucket: 'alu-internship-app-63f4e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_48USKDehaFvcFFWvYbg6gb1k9yMABEY',
    appId: '1:1049365967745:android:f0b486060afb2ad7292e80',
    messagingSenderId: '1049365967745',
    projectId: 'alu-internship-app-63f4e',
    storageBucket: 'alu-internship-app-63f4e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJHT4xmlHAl4VOgabc5AaNS6YiSDpIIBA',
    appId: '1:1049365967745:ios:06b0f6b2e228db3a292e80',
    messagingSenderId: '1049365967745',
    projectId: 'alu-internship-app-63f4e',
    storageBucket: 'alu-internship-app-63f4e.firebasestorage.app',
    iosBundleId: 'com.example.aluInternshipApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJHT4xmlHAl4VOgabc5AaNS6YiSDpIIBA',
    appId: '1:1049365967745:ios:06b0f6b2e228db3a292e80',
    messagingSenderId: '1049365967745',
    projectId: 'alu-internship-app-63f4e',
    storageBucket: 'alu-internship-app-63f4e.firebasestorage.app',
    iosBundleId: 'com.example.aluInternshipApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX1hc2Y4AmDvR4rpYaRQ4JsIp_HjkVa3k',
    appId: '1:1049365967745:web:bdd063b7dcc827f7292e80',
    messagingSenderId: '1049365967745',
    projectId: 'alu-internship-app-63f4e',
    authDomain: 'alu-internship-app-63f4e.firebaseapp.com',
    storageBucket: 'alu-internship-app-63f4e.firebasestorage.app',
  );
}
